import re
import xml.etree.ElementTree as ET

xml = '<IVR><ANI>0889793858</ANI><REQUEST_COMPLETED>1</REQUEST_COMPLETED><REASON>0</REASON><REMAINING_TIMES><REMAINING_TIME_RECORD><TOTAL_TIME>30000</TOTAL_TIME><REMAINING_TIME>26220</REMAINING_TIME><TYPE>offnet</TYPE></REMAINING_TIME_RECORD><REMAINING_TIME_RECORD><TOTAL_TIME>502</TOTAL_TIME><REMAINING_TIME>486</REMAINING_TIME><TYPE>extra_UMB</TYPE></REMAINING_TIME_RECORD><REMAINING_TIME_RECORD><TOTAL_TIME>4395</TOTAL_TIME><REMAINING_TIME>4395</REMAINING_TIME><TYPE>DATA_BUNDLE_5</TYPE></REMAINING_TIME_RECORD><REMAINING_TIME_RECORD><TOTAL_TIME>4395</TOTAL_TIME><REMAINING_TIME>4395</REMAINING_TIME><TYPE>FUP</TYPE></REMAINING_TIME_RECORD><REMAINING_TIME_RECORD><TOTAL_TIME>4395</TOTAL_TIME><REMAINING_TIME>4395</REMAINING_TIME><TYPE>FUPTARIFF</TYPE></REMAINING_TIME_RECORD></REMAINING_TIMES></IVR>'

# open_tag = xml.find('<ANI>')
# closing_tag = xml.find('</ANI>', open_tag)
# ani = xml[open_tag + 5: closing_tag]

# ani = (re.search('<ANI>(.*)</ANI>', xml))
# ani = (ani.group(1))

# open_tag = '<ANI>'
# closing_tag = '</ANI>'
# ani = xml[xml.find(open_tag)+len(open_tag):xml.rfind(closing_tag)]

# tree = ET.fromstring(xml)
# ani = tree.find('REQUEST_COMPLETED').text
