main_data_units = [
    'Sites',
    'Catalogs',
    'Price Books',
    'Inventory Lists',
    'Global Data'
]

sites = [
    'nars_emea',
    'nars_uk',
    'shiseido_global_be',
    'shiseido_global_de',
    'shiseido_global_es',
    'shiseido_global_fr',
    'shiseido_global_it',
    'shiseido_global_uk',
    'lauramercier_uk',
    'isseymiyake_fr',
    'isseymiyake_uk',
    'isseymiyake_de',
    'isseymiyake_es',
    'isseymiyake_zh',
    'isseymiyake_jp',
    'drunkelephant_fr',
    'drunkelephant_de',
    'drunkelephant_uk'
]

sites_units = [
    'A/B Tests',
    'Active Data Feeds',
    'Cache Settings',
    'Campaigns and Promotions',
    'Content',
    'Coupons',
    'Customer CDN Settings',
    'Customer Groups',
    'Custom Objects',
    'Dynamic File Resources',
    'Distributed Commerce Extensions',
    'OCAPI Settings',
    'Payment Methods',
    'Payment Processors',
    'Redirect URLs',
    'Search Settings',
    'Shipping',
    'Site Descriptor',
    'Site Preferences',
    'Static, Dynamic and Alias Mappings',
    'Sitemap Settings',
    'Slots',
    'Sorting Rules',
    'Source Codes',
    'Stores',
    'Tax',
    'URL Rules'
]

catalogs = [
    'BM_MASTER_CATALOG',
    'itemmaster_NARS',
    'itemmaster_drunkelephant',
    'itemmaster_isseymiyake',
    'itemmaster_lauramercier_emea',
    'itemmaster_shiseido_emea',
    'navigation-shiseido-global_be',
    'navigation-shiseido-global_de',
    'navigation-shiseido-global_es',
    'navigation-shiseido-global_fr',
    'navigation-shiseido-global_it',
    'navigation-shiseido-global_nl',
    'navigation-shiseido-global_uk',
    'navigation_NARS_EMEA',
    'navigation_NARS_UK',
    'navigation_isseymiyake',
    'navigation_lauramercier_uk'
]

price_books = [
    'drunkelephant-global_eur-base-price_fr',
    'drunkelephant-global_eur-base-price_uk',
    'drunkelephant-global_gbp-base-price_de',
    'lauramercier-gbp-list-prices',
    'lauramercier-gbp-sale-prices',
    'nars-eur-list-prices',
    'nars-gbp-list-prices',
    'nars-uk-eur-list-prices',
    'shiseido-bnl-sale-prices',
    'shiseido-es-2020-prices',
    'shiseido-es-sale-prices',
    'shiseido-fr-sale-prices',
    'shiseido-global-base-price',
    'shiseido-global-sale-price',
    'shiseido-global_eur-base-price_be',
    'shiseido-global_eur-base-price_de',
    'shiseido-global_eur-base-price_de_vat16',
    'shiseido-global_eur-base-price_es',
    'shiseido-global_eur-base-price_fr',
    'shiseido-global_eur-base-price_it',
    'shiseido-global_gbp-base-price_uk',
    'shiseido-it-sale-prices',
    'shiseido-uk-boxing-day'
]

inventory_lists = [
    'DERET-DRUNKELEPHANT-INVENTORY',
    'DERET-NARS-INVENTORY',
    'INVENTORY_SHISEIDO_GLOBAL_EMEA',
    'INVENTORY_SHISEIDO_GLOBAL_UK',
    'XPO-DRUNKELEPHANT-INVENTORY',
    'XPO-NARS-INVENTORY',
    'inventory_isseymiyake',
    'inventory_lauramercier_uk',
    'inventory_shiseido_global'
]

global_data = [
    'Locales',
    'Preferences',
    'Global Custom Objects',
    'Jobs',
    'Meta Data',
    'Static Resources',
    'Users',
    'Access Roles',
    'Geolocations',
    'Custom Quota Settings',
    'OAuth Providers',
    'OCAPI Settings',
    'WebDAV Client Permissions',
    'Services',
    'CSC Settings',
    'Page Meta Tags',
    'Price Adjustment Limits',
    'CSRF Allowlists',
    'Sorting Rules',
]
